export const careerData = [
  {
    id: "1",
    title: "Senior Solar Engineer",
    jobId: "JOB-001-ENG",
    type: "Full Time",
    requirements: "B.E/B.Tech in Electrical, Mechanical, or Renewable Energy; 3-5 yrs experience in solar design",
    level: "Senior",
    salary: "8 - 12 Lacs P.A.",
    location: "Chennai",
    description:
      "We are looking for an experienced Solar Engineer to lead the design and implementation of large-scale solar projects. You will work with cross-functional teams to optimize PV system performance and ensure project success.",
    responsibilities: [
      "Design and optimize solar PV systems using industry-standard software",
      "Conduct feasibility studies and technical assessments for renewable energy projects",
      "Lead technical teams and mentor junior engineers",
      "Prepare technical documentation and project proposals",
      "Ensure compliance with international standards and regulations",
      "Monitor project progress and troubleshoot technical issues",
    ],
    skills: [
      "PV Design Software (PVsyst, HOMER, SAM)",
      "Electrical Design and Analysis",
      "Project Management",
      "BESS System Design",
      "CAD (AutoCAD, BIM)",
      "Strong communication skills",
    ],
    additionalInfo:
      "Send your complete CV with expected salary to hr@renfraenergy.com mentioning the Job ID and vacancy in the subject. Please note that only shortlisted candidates will be contacted.",
  },
  {
    id: "2",
    title: "Wind Energy Specialist",
    jobId: "JOB-002-WIND",
    type: "Full Time",
    requirements: "B.E/B.Tech in Mechanical or Electrical; 2-4 years experience in wind projects",
    level: "Mid",
    salary: "6 - 10 Lacs P.A.",
    location: "Chennai",
    description:
      "Join our Wind Energy team to develop and manage wind farm projects. You will be responsible for site assessment, turbine selection, and optimization of wind energy systems.",
    responsibilities: [
      "Conduct wind resource assessment and site analysis",
      "Select appropriate turbine technology for project requirements",
      "Prepare wind farm design and layout",
      "Coordinate with equipment suppliers and installation teams",
      "Perform performance monitoring and optimization",
      "Prepare technical reports and feasibility studies",
    ],
    skills: [
      "Wind Energy Software (WAsP, OpenWind)",
      "Site Assessment and Resource Evaluation",
      "Mechanical Design",
      "Data Analysis",
      "Project Coordination",
      "Technical Report Writing",
    ],
    additionalInfo:
      "Send your complete CV with expected salary to hr@renfraenergy.com mentioning the Job ID and vacancy in the subject. Please note that only shortlisted candidates will be contacted.",
  },
  {
    id: "3",
    title: "Energy Storage Systems Engineer",
    jobId: "JOB-003-ESS",
    type: "Full Time",
    requirements: "B.E/B.Tech in Electrical or Electronics; 2-3 years experience with battery systems",
    level: "Mid",
    salary: "5 - 8 Lacs P.A.",
    location: "Chennai",
    description:
      "We seek an Energy Storage Systems Engineer to design and implement BESS solutions. You will work on battery management systems and integrate storage with renewable energy sources.",
    responsibilities: [
      "Design Battery Energy Storage Systems (BESS)",
      "Develop battery management system (BMS) specifications",
      "Perform energy management system (EMS) integration",
      "Conduct efficiency and performance testing",
      "Troubleshoot system issues and provide technical support",
      "Stay updated with latest battery technology trends",
    ],
    skills: [
      "Battery Technology (Li-ion, Lead-acid)",
      "BMS Software and Hardware",
      "EMS Integration",
      "Electrical Engineering",
      "Control Systems",
      "Testing and Validation",
    ],
    additionalInfo:
      "Send your complete CV with expected salary to hr@renfraenergy.com mentioning the Job ID and vacancy in the subject. Please note that only shortlisted candidates will be contacted.",
  },
  {
    id: "4",
    title: "Project Coordinator",
    jobId: "JOB-004-PM",
    type: "Full Time",
    requirements: "Bachelor's degree; 1-3 years experience in project management or coordination",
    level: "Fresher/Entry",
    salary: "3 - 5 Lacs P.A.",
    location: "Chennai",
    description:
      "Join our Project Management team to coordinate renewable energy projects from planning to execution. You will support project managers and ensure smooth project delivery.",
    responsibilities: [
      "Assist in project planning and scheduling",
      "Coordinate between different teams and stakeholders",
      "Track project progress and budgets",
      "Prepare project reports and documentation",
      "Manage project resources and timelines",
      "Support project manager in daily operations",
    ],
    skills: [
      "Project Management Tools (MS Project, Asana)",
      "Communication and Coordination",
      "Documentation Skills",
      "Time Management",
      "Problem-solving",
      "Attention to Detail",
    ],
    additionalInfo:
      "Send your complete CV with expected salary to hr@renfraenergy.com mentioning the Job ID and vacancy in the subject. Please note that only shortlisted candidates will be contacted.",
  },
]
